[package]
name = "mantis_expression"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
log = "0.4.22"
logos = "0.14.2"
rand = "0.8.5"
mantis_tokens = { path = "../mantis_tokens" }
smallstring = "0.1.2"
pest = "2.7.15"
pest_derive = "2.7.15"
linear-map = "1.2.0"
